"""adding assistance id to inclusion case table

Revision ID: 0856b39657dd
Revises: c216f2a81572
Create Date: 2021-12-22 07:05:44.884397

"""
from alembic import op
import sqlalchemy as sa



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inclusion_case', 'assistance_names')
    op.drop_column('inclusion_case', 'assistance_id')
    # ### end Alembic commands ###
 
