"""adding social case number to inclusion case table

Revision ID: 2042022d81c8
Revises: 272b06d50e41
Create Date: 2022-01-06 13:22:58.156510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2042022d81c8'
down_revision = '272b06d50e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inclusion_case', sa.Column('social_case_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inclusion_case', 'social_case_number')
    # ### end Alembic commands ###
