"""adding rejection table

Revision ID: 20e97063a042
Revises: cc0edd24b40c
Create Date: 2021-12-24 04:52:10.819685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e97063a042'
down_revision = 'cc0edd24b40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inclusion_case_rejection',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('analyst_id', sa.Integer(), nullable=False),
                    sa.Column('analyst_names', sa.String(
                        length=120), nullable=False),
                    sa.Column('comments', sa.String(
                        length=800), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_unique_constraint(None, 'approbation', ['id'])
    op.create_unique_constraint(None, 'approbation_attachment', ['id'])
    op.add_column('inclusion_case', sa.Column(
        'rejection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inclusion_case', 'inclusion_case_rejection', [
                          'rejection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inclusion_case', type_='foreignkey')
    op.drop_column('inclusion_case', 'rejection_id')
    op.drop_constraint(None, 'approbation_attachment', type_='unique')
    op.drop_constraint(None, 'approbation', type_='unique')
    op.drop_table('inclusion_case_rejection')
    # ### end Alembic commands ###
