"""adding close table

Revision ID: 227ee0ccd214
Revises: 20e97063a042
Create Date: 2021-12-24 05:09:21.095786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227ee0ccd214'
down_revision = '20e97063a042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inclusion_case_close',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comments', sa.String(length=800), nullable=False),
    sa.Column('assistance_id', sa.Integer(), nullable=False),
    sa.Column('assistance_names', sa.String(length=150), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('inclusion_case', sa.Column('close_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inclusion_case', 'inclusion_case_close', ['close_id'], ['id'])
    op.create_unique_constraint(None, 'inclusion_case_rejection', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inclusion_case_rejection', type_='unique')
    op.drop_constraint(None, 'inclusion_case', type_='foreignkey')
    op.drop_column('inclusion_case', 'close_id')
    op.drop_table('inclusion_case_close')
    # ### end Alembic commands ###
