"""adding inclusion table and attachment table

Revision ID: 53aed1caa242
Revises: b2cb5a6ada8d
Create Date: 2021-12-21 00:16:52.198864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53aed1caa242'
down_revision = 'b2cb5a6ada8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('file_key', sa.String(length=40), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.String(length=20), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inclusion_case',
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_rut', sa.String(length=12), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_names', sa.String(length=250), nullable=False),
    sa.Column('business_rut', sa.String(length=12), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False),
    sa.Column('construction_name', sa.String(length=120), nullable=False),
    sa.Column('interlocutor_id', sa.Integer(), nullable=False),
    sa.Column('authorizing_user', sa.String(length=250), nullable=False),
    sa.Column('authorizing_charge_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('delegation', sa.String(length=120), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('boss_names', sa.String(length=120), nullable=False),
    sa.Column('charge_method_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['charge_method_id'], ['charge_method.id'], ),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number')
    )
    op.create_unique_constraint(None, 'charge_method', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charge_method', type_='unique')
    op.drop_table('inclusion_case')
    op.drop_table('attachment')
    # ### end Alembic commands ###
