"""adding assistance id to inclusion case table

Revision ID: 551c75c91348
Revises: 0856b39657dd
Create Date: 2021-12-22 07:11:16.340188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551c75c91348'
down_revision = '0856b39657dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inclusion_case', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###

    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inclusion_case', 'is_active')
    # ### end Alembic commands ###
 
