"""adding assistance id to inclusion case table

Revision ID: 551c75c91348
Revises: 0856b39657dd
Create Date: 2021-12-22 07:11:16.340188

"""
from alembic import op
import sqlalchemy as sa



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inclusion_case', 'is_active')
    # ### end Alembic commands ###
 
