"""adding attachment id at inclusion case table

Revision ID: c216f2a81572
Revises: 53aed1caa242
Create Date: 2021-12-22 06:33:38.999522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c216f2a81572'
down_revision = '53aed1caa242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'attachment', ['id'])
    op.add_column('inclusion_case', sa.Column('attachment_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'inclusion_case', ['number'])
    op.create_foreign_key(None, 'inclusion_case', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inclusion_case', type_='foreignkey')
    op.drop_constraint(None, 'inclusion_case', type_='unique')
    op.drop_column('inclusion_case', 'attachment_id')
    op.drop_constraint(None, 'attachment', type_='unique')
    # ### end Alembic commands ###
