"""adding approbation tables

Revision ID: cc0edd24b40c
Revises: 551c75c91348
Create Date: 2021-12-24 04:11:41.027609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0edd24b40c'
down_revision = '551c75c91348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approbation',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('analyst_id', sa.Integer(), nullable=False),
                    sa.Column('analyst_names', sa.String(
                        length=120), nullable=False),
                    sa.Column('comments', sa.String(
                        length=800), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('approbation_attachment',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('date', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('attachment_name', sa.String(
                        length=120), nullable=True),
                    sa.Column('attachment_id', sa.Integer(), nullable=False),
                    sa.Column('approbation_id', sa.Integer(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('updated_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('update_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['approbation_id'], [
                                            'approbation.id'], ),
                    sa.ForeignKeyConstraint(
                        ['attachment_id'], ['attachment.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.add_column('inclusion_case', sa.Column(
        'approbation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inclusion_case', 'approbation', [
                          'approbation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inclusion_case', type_='foreignkey')
    op.drop_column('inclusion_case', 'approbation_id')
    op.drop_table('approbation_attachment')
    op.drop_table('approbation')
    # ### end Alembic commands ###
